version: "2"
services:
  subspace:
    image: unafraid/subspace:latest
    container_name: subspace
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /usr/bin/wg:/usr/bin/wg
      - ./data:/data
    environment:
      - SUBSPACE_HTTP_HOST=localhost
      - SUBSPACE_HTTP_ADDR=:80
      - SUBSPACE_HTTP_INSECURE=true
      - SUBSPACE_LETSENCRYPT=false
      - SUBSPACE_WIREGUARD_PORT=51820
      - SUBSPACE_CLIENT_IPV4_SUBNET=192.168.100.0/24
      - SUBSPACE_CLIENT_IPV4_GATEWAY=192.168.100.1
      - SUBSPACE_CLIENT_IPV4_USE_GATEWAY=false
      - SUBSPACE_CLIENT_IPV4_DNS=192.168.100.1
      - SUBSPACE_CLIENT_IPV4_USE_DNS=false
      - SUBSPACE_CLIENT_IPV6_ENABLED=false
      - SUBSPACE_CLIENT_IPV6_SUBNET=fd00::10:97:0/112
      - SUBSPACE_CLIENT_IPV6_GATEWAY=fd00::10:97:1
      - SUBSPACE_CLIENT_IPV6_USE_GATEWAY=false
      - SUBSPACE_CLIENT_IPV6_DNS=fd00::10:97:1
      - SUBSPACE_CLIENT_IPV6_USE_DNS=false
      - SUBSPACE_CLIENT_KEEP_ALIVE=25
